### ISSUE TITLE
Question about "all" model and results

### ISSUE THREAD

**Issue by MohammedSB** [mlmed/torchxrayvision#139]
Hello,

So I know that the "all model" is trained on multiple datasets, but is it trained on the entirety of those datasets (all training examples) or just a subset?
Also, I wanted to ask where I can find the results of this model on all of the test sets, **including NIH**.
I am not sure how to interpret the benchmark results in the markdown, it says:

> Below is an example of running different models on the nih dataset and writing the output as markdown.

But in the markdown, none of the titles for the tables is for NIH.

**Comment by ieee8023** [comment]
It is trained on a subset (I think 80%) but the split is lost so consider it to be all samples. 

It seems I didn't run the benchmarks on the NIH dataset. I'll try to get to that soon.

I fixed the typo which should have said PadChest instead of NIH. So that example runs those models on the PadChest dataset and this results in a row for the results of each model.

**Comment by ieee8023** [comment]
I added benchmark results for the NIH dataset for 3 models. The chexpert model is running now but it might take a day or so.

**Comment by MohammedSB** [comment]
Thank you very much!
I really only needed the results for the all model.
